# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import audio_pb2 as proto_dot_audio__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUserVoice = channel.unary_unary(
                '/proto.AudioService/AddUserVoice',
                request_serializer=proto_dot_audio__pb2.AddUserVoiceRequest.SerializeToString,
                response_deserializer=proto_dot_audio__pb2.AddUserVoiceResponse.FromString,
                _registered_method=True)
        self.TTS = channel.unary_unary(
                '/proto.AudioService/TTS',
                request_serializer=proto_dot_audio__pb2.TTSRequest.SerializeToString,
                response_deserializer=proto_dot_audio__pb2.TTSResponse.FromString,
                _registered_method=True)
        self.VoiceConversion = channel.unary_unary(
                '/proto.AudioService/VoiceConversion',
                request_serializer=proto_dot_audio__pb2.VoiceConversionRequest.SerializeToString,
                response_deserializer=proto_dot_audio__pb2.VoiceConversionResponse.FromString,
                _registered_method=True)
        self.ASR = channel.unary_unary(
                '/proto.AudioService/ASR',
                request_serializer=proto_dot_audio__pb2.ASRRequest.SerializeToString,
                response_deserializer=proto_dot_audio__pb2.ASRResponse.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUserVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoiceConversion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ASR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUserVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserVoice,
                    request_deserializer=proto_dot_audio__pb2.AddUserVoiceRequest.FromString,
                    response_serializer=proto_dot_audio__pb2.AddUserVoiceResponse.SerializeToString,
            ),
            'TTS': grpc.unary_unary_rpc_method_handler(
                    servicer.TTS,
                    request_deserializer=proto_dot_audio__pb2.TTSRequest.FromString,
                    response_serializer=proto_dot_audio__pb2.TTSResponse.SerializeToString,
            ),
            'VoiceConversion': grpc.unary_unary_rpc_method_handler(
                    servicer.VoiceConversion,
                    request_deserializer=proto_dot_audio__pb2.VoiceConversionRequest.FromString,
                    response_serializer=proto_dot_audio__pb2.VoiceConversionResponse.SerializeToString,
            ),
            'ASR': grpc.unary_unary_rpc_method_handler(
                    servicer.ASR,
                    request_deserializer=proto_dot_audio__pb2.ASRRequest.FromString,
                    response_serializer=proto_dot_audio__pb2.ASRResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUserVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AudioService/AddUserVoice',
            proto_dot_audio__pb2.AddUserVoiceRequest.SerializeToString,
            proto_dot_audio__pb2.AddUserVoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AudioService/TTS',
            proto_dot_audio__pb2.TTSRequest.SerializeToString,
            proto_dot_audio__pb2.TTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VoiceConversion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AudioService/VoiceConversion',
            proto_dot_audio__pb2.VoiceConversionRequest.SerializeToString,
            proto_dot_audio__pb2.VoiceConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ASR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AudioService/ASR',
            proto_dot_audio__pb2.ASRRequest.SerializeToString,
            proto_dot_audio__pb2.ASRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
